---
title: "Publications"
editor: visual
---

**Ouedraogo, I.**, Oueda, A., Sirima, D., Ouedraogo, I., Guenda, W. & Kabre, G. B. (2015). Assessment of benthic molluscs diversity and distribution in urban reservoirs (Ouagadougou, Burkina Faso). *International Journal of Biological and Chemical Sciences, 9*(4). https://doi.org/10.4314/ijbcs.v9i4.29

Kaboré, I., Ouedraogo, I., Tampo, L., Ouéda, A., Moog, O., Guenda, W. & Melcher, A. (2017). Composition and dynamic of benthic macroinvertebrates community in semi-arid area rivers of Burkina Faso (West Africa). *, 10*. https://doi.org/10.4314/ijbcs.v10i4.8

Bancé, V., Adama, O., Kaboré, I., Ouedraogo, I., Mano, K., Weesie, P. & Kabré, G. (2021). Influence of micro-habitats on the distribution of macroinvertebrates in Burkina Faso (West Africa). *, 9*. https://doi.org/10.22034/ijab.v9i3.976

Dabone, C., Oueda, A., Adjakpa, J. B., Buij, R., Ouedraogo, I., Guenda, W. & Weesie, P. D. M. (2016). Phénologie de la reproduction du Vautour charognard Necrosyrtes monachus en zone soudano sahélienne (Garango, Burkina Faso), 2013–2015.. . https://www.rug.nl/research/portal/publications/phenologie-de-la-reproduction-du-vautour-charognard-necrosyrtes-monachus-en-zone-soudano-sahelienne-garango-burkina-faso-20132015(93e5576f-0d83-454b-ae7a-0cdd13219f08)/export.html


Mano, K., Oueda, A., Ouedraogo, R., Ouedraogo, I., Kaboré, I., Kabre, G. B. & Melcher, A. (2020). Fish assemblages in the Upper part of the Volta River, Burkina Faso: A link analysis towards fisheries management and conservation. International Journal of Biological and Chemical Sciences, 13. https://doi.org/10.4314/ijbcs.v13i6.11


Kpoda, N. W., Darimani, H. S., Ouéda, A., Ouedraogo, I. & Kabré, G. (2022). Risk of Waterborne Parasitic Infection among Vegetables Producers in the City of Ouagadougou, Burkina Faso: An Attempt to Quantify Them Using the Quantitative Microbiological Risk Assessment Method. Agricultural Science. https://doi.org/10.4236/as.2022.131002


Dao, Z. A., Romba, R., Traoré, M., Birba, S., Zoure, A. B., Ouedraogo, I., Ouédraogo, A. & Gnankiné, O. (2022). Diversity and Role of Entomological Fauna Associated With Annona senegalensis (Magnoliales: Annonaceae) in Burkina Faso, West Africa. Environmental Entomology. https://doi.org/10.1093/ee/nvac040

Ouédraogo, I., Ouedraogo, I., Kpoda, N., Ouéda, A., Bancé, V., Kaboré, J. & Kabre, G. B. (2020). Impact of road construction on the distribution of Crocodylus suchus (Étienne Geoffroy Saint-Hilaire 1807) in urban park Bangr-Weoogo (Burkina Faso). undefined, 14. https://doi.org/10.4314/ijbcs.v14i2.7

Silga, R. P., Ouéda, A., Kpoda, W. N., Mano, K., Ouedraogo, I., Weesie, D. M. P. & Kabre, B. G. (2021). Fishermen Local Knowledge and Aquatic Environmental Change: Impacts on Fishing and Adaptation Strategies in Volta Basin. Open Journal of Ecology, 11(07). https://doi.org/10.4236/oje.2021.117033

Ouedraogo, I., Kpoda, N., Ouéda, A., Bancé, V., Mano, K. & Kabré, G. (2023). Establishment of an invasive snail Melanoides tuberculata (Müller, 1774) in a Sahelian urban reservoir in Ouagadougou, Burkina Faso. BioInvasions Records. https://doi.org/10.3391/bir.2023.12.3.15

Kangoyé, N. M., Oueda, A., Silga, R. P., Ouedraogo, I., Di Vittorio, M. & Kabre, B. G. (2021). Modeling Bat Species Richness and Spatial Distribution in Burkina Faso. undefined. https://doi.org/10.4236/oje.2021.1111048


Ouédraogo, I., Ouedraogo, I., Kpoda, N., Ouéda, A., Bancé, V., Kaboré, J. & Kabre, G. B. (2020). Impact of road construction on the distribution of Crocodylus suchus (Étienne Geoffroy Saint-Hilaire 1807) in urban park Bangr-Weoogo (Burkina Faso). undefined, 14. https://doi.org/10.4314/ijbcs.v14i2.7


